/* File generated by ../png2rgb/png2rgb. */
#ifndef _BACK_H_
#define _BACK_H_

/** Image width. */
#define BACK_WIDTH 32
/** Image height. */
#define BACK_HEIGHT 32
/** Color depth, maximum color value. */
#define BACK_DEPTH 4

#endif /* _BACK_H_ */
