/* File generated by ../png2rgb/png2rgb. */
#ifndef _BARFILL_H_
#define _BARFILL_H_

/** Image width. */
#define BARFILL_WIDTH 260
/** Image height. */
#define BARFILL_HEIGHT 18
/** Color depth, maximum color value. */
#define BARFILL_DEPTH 4

#endif /* _BARFILL_H_ */
