/* File generated by ../png2rgb/png2rgb. */
#ifndef _BARTRACK_H_
#define _BARTRACK_H_

/** Image width. */
#define BARTRACK_WIDTH 260
/** Image height. */
#define BARTRACK_HEIGHT 18
/** Color depth, maximum color value. */
#define BARTRACK_DEPTH 4

#endif /* _BARTRACK_H_ */
