/* File generated by ../png2rgb/png2rgb. */
#ifndef _BOTTOMBAR_H_
#define _BOTTOMBAR_H_

/** Image width. */
#define BOTTOMBAR_WIDTH 640
/** Image height. */
#define BOTTOMBAR_HEIGHT 34
/** Color depth, maximum color value. */
#define BOTTOMBAR_DEPTH 4

#endif /* _BOTTOMBAR_H_ */
