/* File generated by ../png2rgb/png2rgb. */
#ifndef _DISC_H_
#define _DISC_H_

/** Image width. */
#define DISC_WIDTH 161
/** Image height. */
#define DISC_HEIGHT 107
/** Color depth, maximum color value. */
#define DISC_DEPTH 4

#endif /* _DISC_H_ */
