/* File generated by ../png2rgb/png2rgb. */
#ifndef _FOLDER_H_
#define _FOLDER_H_

/** Image width. */
#define FOLDER_WIDTH 32
/** Image height. */
#define FOLDER_HEIGHT 32
/** Color depth, maximum color value. */
#define FOLDER_DEPTH 4

#endif /* _FOLDER_H_ */
