/* File generated by ../png2rgb/png2rgb. */
#ifndef _HIGHLIGHT_H_
#define _HIGHLIGHT_H_

/** Image width. */
#define HIGHLIGHT_WIDTH 338
/** Image height. */
#define HIGHLIGHT_HEIGHT 26
/** Color depth, maximum color value. */
#define HIGHLIGHT_DEPTH 4

#endif /* _HIGHLIGHT_H_ */
