/* File generated by ../png2rgb/png2rgb. */
#ifndef _PANEL_H_
#define _PANEL_H_

/** Image width. */
#define PANEL_WIDTH 224
/** Image height. */
#define PANEL_HEIGHT 188
/** Color depth, maximum color value. */
#define PANEL_DEPTH 4

#endif /* _PANEL_H_ */
