/* File generated by ../png2rgb/png2rgb. */
#ifndef _PENGUIN_H_
#define _PENGUIN_H_

/** Image width. */
#define PENGUIN_WIDTH 128
/** Image height. */
#define PENGUIN_HEIGHT 128
/** Color depth, maximum color value. */
#define PENGUIN_DEPTH 4

#endif /* _PENGUIN_H_ */
