extern unsigned char ps2dev9_irx[];
extern int size_ps2dev9_irx;
extern unsigned char fileXio_irx[];
extern int size_fileXio_irx;
extern unsigned char iomanX_irx[];
extern int size_iomanX_irx;
extern unsigned char ioptrap_irx[];
extern int size_ioptrap_irx;
extern unsigned char poweroff_irx[];
extern int size_poweroff_irx;
extern unsigned char ps2ip_irx[];
extern int size_ps2ip_irx;
extern unsigned char ps2http_irx[];
extern int size_ps2http_irx;
extern unsigned char sharedmem_irx[];
extern int size_sharedmem_irx;
extern unsigned char smaprpc_irx[];
extern int size_smaprpc_irx;
extern unsigned char dev9init_irx[];
extern int size_dev9init_irx;
extern unsigned char usbd_irx[];
extern int size_usbd_irx;
extern unsigned char bdm_irx[];
extern int size_bdm_irx;
extern unsigned char bdmfs_fatfs_irx[];
extern int size_bdmfs_fatfs_irx;
extern unsigned char usbmass_bd_irx[];
extern int size_usbmass_bd_irx;
extern unsigned char ps2kbd_irx[];
extern int size_ps2kbd_irx;
extern unsigned char SMSUTILS_irx[];
extern int size_SMSUTILS_irx;
extern unsigned char SMSCDVD_irx[];
extern int size_SMSCDVD_irx;
extern unsigned char eromdrvloader_irx[];
extern int size_eromdrvloader_irx;
extern unsigned char TGE_sbios_old_elf[];
extern int size_TGE_sbios_old_elf;
extern unsigned char TGE_sbios_new_elf[];
extern int size_TGE_sbios_new_elf;
extern unsigned char TGE_intrelay_direct_irx[];
extern int size_TGE_intrelay_direct_irx;
extern unsigned char TGE_intrelay_direct_rpc_irx[];
extern int size_TGE_intrelay_direct_rpc_irx;
extern unsigned char TGE_intrelay_dev9_irx[];
extern int size_TGE_intrelay_dev9_irx;
extern unsigned char TGE_intrelay_dev9_rpc_irx[];
extern int size_TGE_intrelay_dev9_rpc_irx;
extern unsigned char kernel_elf[];
extern int size_kernel_elf;
extern unsigned char mcicons_icon_sys[];
extern int size_mcicons_icon_sys;
extern unsigned char mcicons_kloader_icn[];
extern int size_mcicons_kloader_icn;
extern unsigned char folder_rgb[];
extern int size_folder_rgb;
extern unsigned char penguin_rgb[];
extern int size_penguin_rgb;
extern unsigned char up_rgb[];
extern int size_up_rgb;
extern unsigned char back_rgb[];
extern int size_back_rgb;
extern unsigned char selected_rgb[];
extern int size_selected_rgb;
extern unsigned char unselected_rgb[];
extern int size_unselected_rgb;
extern unsigned char disc_rgb[];
extern int size_disc_rgb;
extern unsigned char starfield_rgb[];
extern int size_starfield_rgb;
extern unsigned char title_rgb[];
extern int size_title_rgb;
extern unsigned char bottombar_rgb[];
extern int size_bottombar_rgb;
extern unsigned char panel_rgb[];
extern int size_panel_rgb;
extern unsigned char highlight_rgb[];
extern int size_highlight_rgb;
extern unsigned char bartrack_rgb[];
extern int size_bartrack_rgb;
extern unsigned char barfill_rgb[];
extern int size_barfill_rgb;
