#include "folder.h"
#include "penguin.h"
#include "up.h"
#include "back.h"
#include "selected.h"
#include "unselected.h"
#include "disc.h"
#include "starfield.h"
#include "title.h"
#include "bottombar.h"
#include "panel.h"
#include "highlight.h"
#include "bartrack.h"
#include "barfill.h"
rom_files[i].start = ps2dev9_irx;
rom_files[i].size = size_ps2dev9_irx;
i++;
rom_files[i].start = fileXio_irx;
rom_files[i].size = size_fileXio_irx;
i++;
rom_files[i].start = iomanX_irx;
rom_files[i].size = size_iomanX_irx;
i++;
rom_files[i].start = ioptrap_irx;
rom_files[i].size = size_ioptrap_irx;
i++;
rom_files[i].start = poweroff_irx;
rom_files[i].size = size_poweroff_irx;
i++;
rom_files[i].start = ps2ip_irx;
rom_files[i].size = size_ps2ip_irx;
i++;
rom_files[i].start = ps2http_irx;
rom_files[i].size = size_ps2http_irx;
i++;
rom_files[i].start = sharedmem_irx;
rom_files[i].size = size_sharedmem_irx;
i++;
rom_files[i].start = smaprpc_irx;
rom_files[i].size = size_smaprpc_irx;
i++;
rom_files[i].start = dev9init_irx;
rom_files[i].size = size_dev9init_irx;
i++;
rom_files[i].start = usbd_irx;
rom_files[i].size = size_usbd_irx;
i++;
rom_files[i].start = bdm_irx;
rom_files[i].size = size_bdm_irx;
i++;
rom_files[i].start = bdmfs_fatfs_irx;
rom_files[i].size = size_bdmfs_fatfs_irx;
i++;
rom_files[i].start = usbmass_bd_irx;
rom_files[i].size = size_usbmass_bd_irx;
i++;
rom_files[i].start = ps2kbd_irx;
rom_files[i].size = size_ps2kbd_irx;
i++;
rom_files[i].start = SMSUTILS_irx;
rom_files[i].size = size_SMSUTILS_irx;
i++;
rom_files[i].start = SMSCDVD_irx;
rom_files[i].size = size_SMSCDVD_irx;
i++;
rom_files[i].start = eromdrvloader_irx;
rom_files[i].size = size_eromdrvloader_irx;
i++;
rom_files[i].start = TGE_sbios_old_elf;
rom_files[i].size = size_TGE_sbios_old_elf;
i++;
rom_files[i].start = TGE_sbios_new_elf;
rom_files[i].size = size_TGE_sbios_new_elf;
i++;
rom_files[i].start = TGE_intrelay_direct_irx;
rom_files[i].size = size_TGE_intrelay_direct_irx;
i++;
rom_files[i].start = TGE_intrelay_direct_rpc_irx;
rom_files[i].size = size_TGE_intrelay_direct_rpc_irx;
i++;
rom_files[i].start = TGE_intrelay_dev9_irx;
rom_files[i].size = size_TGE_intrelay_dev9_irx;
i++;
rom_files[i].start = TGE_intrelay_dev9_rpc_irx;
rom_files[i].size = size_TGE_intrelay_dev9_rpc_irx;
i++;
rom_files[i].start = kernel_elf;
rom_files[i].size = size_kernel_elf;
i++;
rom_files[i].start = mcicons_icon_sys;
rom_files[i].size = size_mcicons_icon_sys;
i++;
rom_files[i].start = mcicons_kloader_icn;
rom_files[i].size = size_mcicons_kloader_icn;
i++;
rom_files[i].start = folder_rgb;
rom_files[i].size = size_folder_rgb;
rom_files[i].width = FOLDER_WIDTH;
rom_files[i].height = FOLDER_HEIGHT;
rom_files[i].depth = FOLDER_DEPTH;
i++;
rom_files[i].start = penguin_rgb;
rom_files[i].size = size_penguin_rgb;
rom_files[i].width = PENGUIN_WIDTH;
rom_files[i].height = PENGUIN_HEIGHT;
rom_files[i].depth = PENGUIN_DEPTH;
i++;
rom_files[i].start = up_rgb;
rom_files[i].size = size_up_rgb;
rom_files[i].width = UP_WIDTH;
rom_files[i].height = UP_HEIGHT;
rom_files[i].depth = UP_DEPTH;
i++;
rom_files[i].start = back_rgb;
rom_files[i].size = size_back_rgb;
rom_files[i].width = BACK_WIDTH;
rom_files[i].height = BACK_HEIGHT;
rom_files[i].depth = BACK_DEPTH;
i++;
rom_files[i].start = selected_rgb;
rom_files[i].size = size_selected_rgb;
rom_files[i].width = SELECTED_WIDTH;
rom_files[i].height = SELECTED_HEIGHT;
rom_files[i].depth = SELECTED_DEPTH;
i++;
rom_files[i].start = unselected_rgb;
rom_files[i].size = size_unselected_rgb;
rom_files[i].width = UNSELECTED_WIDTH;
rom_files[i].height = UNSELECTED_HEIGHT;
rom_files[i].depth = UNSELECTED_DEPTH;
i++;
rom_files[i].start = disc_rgb;
rom_files[i].size = size_disc_rgb;
rom_files[i].width = DISC_WIDTH;
rom_files[i].height = DISC_HEIGHT;
rom_files[i].depth = DISC_DEPTH;
i++;
rom_files[i].start = starfield_rgb;
rom_files[i].size = size_starfield_rgb;
rom_files[i].width = STARFIELD_WIDTH;
rom_files[i].height = STARFIELD_HEIGHT;
rom_files[i].depth = STARFIELD_DEPTH;
i++;
rom_files[i].start = title_rgb;
rom_files[i].size = size_title_rgb;
rom_files[i].width = TITLE_WIDTH;
rom_files[i].height = TITLE_HEIGHT;
rom_files[i].depth = TITLE_DEPTH;
i++;
rom_files[i].start = bottombar_rgb;
rom_files[i].size = size_bottombar_rgb;
rom_files[i].width = BOTTOMBAR_WIDTH;
rom_files[i].height = BOTTOMBAR_HEIGHT;
rom_files[i].depth = BOTTOMBAR_DEPTH;
i++;
rom_files[i].start = panel_rgb;
rom_files[i].size = size_panel_rgb;
rom_files[i].width = PANEL_WIDTH;
rom_files[i].height = PANEL_HEIGHT;
rom_files[i].depth = PANEL_DEPTH;
i++;
rom_files[i].start = highlight_rgb;
rom_files[i].size = size_highlight_rgb;
rom_files[i].width = HIGHLIGHT_WIDTH;
rom_files[i].height = HIGHLIGHT_HEIGHT;
rom_files[i].depth = HIGHLIGHT_DEPTH;
i++;
rom_files[i].start = bartrack_rgb;
rom_files[i].size = size_bartrack_rgb;
rom_files[i].width = BARTRACK_WIDTH;
rom_files[i].height = BARTRACK_HEIGHT;
rom_files[i].depth = BARTRACK_DEPTH;
i++;
rom_files[i].start = barfill_rgb;
rom_files[i].size = size_barfill_rgb;
rom_files[i].width = BARFILL_WIDTH;
rom_files[i].height = BARFILL_HEIGHT;
rom_files[i].depth = BARFILL_DEPTH;
i++;
