/* File generated by ../png2rgb/png2rgb. */
#ifndef _SELECTED_H_
#define _SELECTED_H_

/** Image width. */
#define SELECTED_WIDTH 32
/** Image height. */
#define SELECTED_HEIGHT 32
/** Color depth, maximum color value. */
#define SELECTED_DEPTH 4

#endif /* _SELECTED_H_ */
