/* File generated by ../png2rgb/png2rgb. */
#ifndef _STARFIELD_H_
#define _STARFIELD_H_

/** Image width. */
#define STARFIELD_WIDTH 731
/** Image height. */
#define STARFIELD_HEIGHT 512
/** Color depth, maximum color value. */
#define STARFIELD_DEPTH 3

#endif /* _STARFIELD_H_ */
