/* File generated by ../png2rgb/png2rgb. */
#ifndef _TITLE_H_
#define _TITLE_H_

/** Image width. */
#define TITLE_WIDTH 284
/** Image height. */
#define TITLE_HEIGHT 74
/** Color depth, maximum color value. */
#define TITLE_DEPTH 4

#endif /* _TITLE_H_ */
