/* File generated by ../png2rgb/png2rgb. */
#ifndef _UNSELECTED_H_
#define _UNSELECTED_H_

/** Image width. */
#define UNSELECTED_WIDTH 32
/** Image height. */
#define UNSELECTED_HEIGHT 32
/** Color depth, maximum color value. */
#define UNSELECTED_DEPTH 4

#endif /* _UNSELECTED_H_ */
