/* File generated by ../png2rgb/png2rgb. */
#ifndef _UP_H_
#define _UP_H_

/** Image width. */
#define UP_WIDTH 32
/** Image height. */
#define UP_HEIGHT 32
/** Color depth, maximum color value. */
#define UP_DEPTH 4

#endif /* _UP_H_ */
