#!/usr/bin/env python3
"""Turn a PNG into include/linux/linux_logo.h for the PS2 Linux kernel.

The boot logo is not an image file in the kernel -- it is C arrays compiled
into the image, which is why replacing it needs a build. include/asm-mips/
linux_logo.h states the rules and drivers/video/ps2con.c enforces the size:

    LINUX_LOGO_COLORS has to be less than 224
    image size has to be 80x80
    values have to start from 0x20
    BW image has to be 80x80 as well, with MS bit on the left

Three variants are emitted because the header declares all three and different
console drivers reach for different ones. ps2con.c uses `linux_logo`, the
224-colour one, but fbcon falls back to `linux_logo16` or `linux_logo_bw`
depending on depth, and leaving those describing the old artwork would give a
logo that changes with video mode.

Conversion goes through ImageMagick rather than PIL, which is not installed
here, and lands in PPM -- a format simple enough to parse in a few lines and
therefore one less dependency to be wrong about.

Usage:  png2logo.py assets/penguin.png > include/linux/linux_logo.h
"""

import subprocess
import sys

W = H = 80
MAX_COLORS = 214  # header says < 224; leave headroom, MontaVista used 214
BASE = 0x20  # colour 0 is index 0x20, per the header


def convert(src, args):
    """Run ImageMagick and return the result as (width, height, [(r,g,b)...]).

    The logo is drawn straight onto the console background, so alpha has to be
    resolved here: -flatten composites against black, which is what the PS2
    console clears to. Leaving it unflattened turns transparent pixels into
    whatever the quantiser felt like, usually a white box round the artwork.
    """
    ppm = subprocess.run(
        ["convert", src,
         # Harden alpha before trimming. Artwork with a soft drop shadow trims
         # to almost the full canvas, because the shadow is opaque enough to
         # count as content but too dark to tell from the background -- so the
         # subject ends up shoved into a corner with the shadow padding the
         # rest. Thresholding discards it. Hard edges are no loss at 80x80:
         # semi-transparent fringes only composite to muddy grey anyway.
         "-channel", "A", "-threshold", "50%", "+channel",
         "-trim", "+repage",
         # No "!": preserve aspect, fit inside 80x80, then pad back to square.
         # Forcing the aspect squashes the artwork.
         "-resize", f"{W}x{H}",
         "-background", "black", "-alpha", "remove", "-alpha", "off",
         "-gravity", "center", "-extent", f"{W}x{H}"] + args + ["ppm:-"],
        capture_output=True, check=True).stdout

    # P6 header: magic, width, height, maxval -- whitespace-separated, and
    # comments are legal between them.
    fields, pos = [], 2
    while len(fields) < 3:
        while ppm[pos:pos + 1].isspace():
            pos += 1
        if ppm[pos:pos + 1] == b"#":
            pos = ppm.index(b"\n", pos) + 1
            continue
        end = pos
        while not ppm[end:end + 1].isspace():
            end += 1
        fields.append(int(ppm[pos:end]))
        pos = end
    pos += 1

    w, h, _ = fields
    data = ppm[pos:]
    return w, h, [tuple(data[i:i + 3]) for i in range(0, w * h * 3, 3)]


def emit_array(name, values, per_line=16, fmt="0x%02x"):
    print(f"unsigned char {name}[] __initdata = {{")
    for i in range(0, len(values), per_line):
        chunk = ", ".join(fmt % v for v in values[i:i + per_line])
        print(f"\t{chunk},")
    print("};\n")


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    src = sys.argv[1]

    # +dither is deliberately off. Dithering scatters isolated pixels, which at
    # 80x80 on a 640x448 display reads as noise rather than shading.
    _, _, pixels = convert(src, ["+dither", "-colors", str(MAX_COLORS)])

    palette, index = [], {}
    indices = []
    for px in pixels:
        if px not in index:
            index[px] = len(palette)
            palette.append(px)
        indices.append(index[px] + BASE)

    if len(palette) > MAX_COLORS:
        sys.exit(f"{len(palette)} colours after quantising, limit is {MAX_COLORS}")

    # Emit the WHOLE header, guards included, rather than just the arrays.
    # Splicing generated arrays onto the tail of the original leaves the
    # trailing "#endif /* !INCLUDE_LINUX_LOGO_DATA */" without its opening
    # "#ifdef", and ps2con.o fails to compile. The three __HAVE_ARCH_* guards
    # let an architecture override an individual variant, so they are kept
    # even though mips overrides none of them.
    print("/*\n * include/linux/linux_logo.h -- generated by phase1/png2logo.py\n"
          f" *\n * Source: {src}, {W}x{H}, {len(palette)} colours.\n"
          " * Do not edit by hand; regenerate instead.\n */\n")
    print("#ifndef __HAVE_ARCH_LINUX_LOGO")
    print(f"#define LINUX_LOGO_COLORS\t{len(palette)}")
    print("#endif\n")
    print("#ifdef INCLUDE_LINUX_LOGO_DATA\n")
    print("#ifndef __HAVE_ARCH_LINUX_LOGO")

    emit_array("linux_logo_red", [c[0] for c in palette])
    emit_array("linux_logo_green", [c[1] for c in palette])
    emit_array("linux_logo_blue", [c[2] for c in palette])
    emit_array("linux_logo", indices)
    print("#endif\n")
    print("#ifndef __HAVE_ARCH_LINUX_LOGO16")

    # 16-colour variant for shallower framebuffers.
    _, _, px16 = convert(src, ["+dither", "-colors", "16"])
    pal16, idx16, ind16 = [], {}, []
    for px in px16:
        if px not in idx16:
            idx16[px] = len(pal16)
            pal16.append(px)
        ind16.append(idx16[px] + BASE)
    emit_array("linux_logo16_red", [c[0] for c in pal16])
    emit_array("linux_logo16_green", [c[1] for c in pal16])
    emit_array("linux_logo16_blue", [c[2] for c in pal16])
    emit_array("linux_logo16", ind16)
    print("#endif\n")
    print("#ifndef __HAVE_ARCH_LINUX_LOGOBW")

    # Mono: 8 pixels per byte, most significant bit leftmost, as the header
    # requires. Threshold at 50% -- anything brighter than mid grey is ink.
    _, _, pxbw = convert(src, ["-colorspace", "Gray"])
    bw = []
    for y in range(H):
        for xbyte in range(W // 8):
            byte = 0
            for bit in range(8):
                r, g, b = pxbw[y * W + xbyte * 8 + bit]
                if (r + g + b) // 3 > 127:
                    byte |= 0x80 >> bit
            bw.append(byte)
    emit_array("linux_logo_bw", bw)
    print("#endif\n")

    print("#else /* !INCLUDE_LINUX_LOGO_DATA */\n")
    print("/* prototypes only */")
    for n in ("linux_logo_red", "linux_logo_green", "linux_logo_blue",
              "linux_logo", "linux_logo_bw", "linux_logo16"):
        print(f"extern unsigned char {n}[];")
    print("\n#endif /* !INCLUDE_LINUX_LOGO_DATA */")


if __name__ == "__main__":
    main()
