/* Proportional text from a glyph atlas.
 *
 * Replaces gsKit_fontm_print_scaled, which draws the PS2's BIOS ROM font:
 * one fixed bitmap face, scale as its only knob, and no way to measure a
 * rendered string. That last part is why every text position in graphic.cpp is
 * a hardcoded column tuned by eye, why the System Info panel cannot
 * right-align its values, and why "DVD-Video" had to be shortened to "DVD-V"
 * to stop it running into its own value.
 *
 * The atlas is an ordinary texture drawn with gsKit_prim_sprite_texture -- the
 * same call the starfield and the menu highlight already use -- so this needs
 * no new texture plumbing. Metrics come from loader/fontdata.h, generated by
 * tools/fontgen.py.
 */
#ifndef __FONT_H__
#define __FONT_H__

#include <gsKit.h>

#ifdef __cplusplus
extern "C" {
#endif

/** Load the atlas texture. Call once the GS is up, as with the other textures. */
int fontInit(void);

/** Re-upload after a video mode change, like reallocTexture() does. */
void fontReset(void);

/* The atlas is rasterised well above display size and drawn scaled DOWN. The
 * GS samples it with GS_FILTER_LINEAR, so shrinking a high-resolution glyph
 * supersamples it: noticeably cleaner than rasterising at the final size, which
 * is all the ROM font could ever do. Scales are therefore normally < 1.
 *
 * FONT_MENU and FONT_PANEL are the two sizes the UI uses; anything else is a
 * one-off and should say why at the call site. */
#define FONT_MENU   0.50f
#define FONT_PANEL  0.40f
#define FONT_STATUS 0.42f
#define FONT_TITLE  0.62f
#define FONT_HINT   0.40f
#define FONT_BODY   0.44f

/** Width in pixels the string would occupy at this scale. The whole point of
 * the exercise: gsKit_fontm could not answer this, so nothing could be centred
 * or right-aligned. Unknown characters measure as a space. */
int fontMeasure(const char *text, float scale);

/** Distance between baselines at this scale. */
int fontLineHeight(float scale);

/** Width of a single character. For wrapping a paragraph a glyph at a time,
 * where measuring the whole remaining string per character would be quadratic. */
int fontCharWidth(char c, float scale);

/** Draw with the string's left edge at x, its top at y. */
void fontPrint(int x, int y, int z, u64 colour, const char *text, float scale);

/** Draw centred on cx. */
void fontPrintCentred(int cx, int y, int z, u64 colour, const char *text, float scale);

/** Draw with the string's RIGHT edge at rx. */
void fontPrintRight(int rx, int y, int z, u64 colour, const char *text, float scale);

/** Draw, truncating with an ellipsis if it would exceed maxWidth. Returns the
 * width actually drawn. Long values such as a full ROM version string are the
 * reason this exists. */
int fontPrintClipped(int x, int y, int z, u64 colour, const char *text, int maxWidth, float scale);

#ifdef __cplusplus
}
#endif

#endif /* __FONT_H__ */
